const data = {
  products: [
    {
      name: "productA-Name",
      category: "Pharma",
      description: "",
      price: 100,
      token: "productA-Token",
      brand: "Teva",
      countInStock: 6,
      rating: 2.5,
      numRevies: 100,
      image: "/images/Explosion.png",
    },
    {
      name: "productB-Name",
      category: "Computer",
      description: "",
      price: 300,
      token: "productB-Token",
      brand: "Dell",
      countInStock: 8,
      rating: 4.2,
      numRevies: 150,
      image: "/images/PlayerImage.png",
    },
    {
      name: "productC-Name",
      category: "Computer",
      description: "",
      price: 350,
      token: "productC-Token",
      brand: "Razor",
      countInStock: 2,
      rating: 3.2,
      numRevies: 250,
      image: "/images/EnemyImage.png",
    },
    {
      name: "productD-Name",
      category: "Food",
      description: "",
      price: 90,
      token: "productD-Token",
      brand: "Tnuva",
      countInStock: 150,
      rating: 2.2,
      numRevies: 14,
      image: "/images/EnterKey.png",
    },
  ],
};

export default data;
